### ISSUE TITLE
Labml is stuck

### ISSUE THREAD

**Issue by shetsecure** [lab-ml/labml#60]
I can't do anything with labml, even if it is as simple as executing: 
![image](https://user-images.githubusercontent.com/18449334/117524551-18d21400-afbe-11eb-8be3-5b01a3bf8fbd.png)

It is stuck forever, and I literally downloaded and executed your notebook https://colab.research.google.com/github/lab-ml/labml/blob/master/guides/monitor.ipynb

and it gets stuck at the sixth cell: tracker.set_queue('loss.train', 20, True)

![image](https://user-images.githubusercontent.com/18449334/117524620-6189cd00-afbe-11eb-981b-271bbf5a8abf.png)

What should I do please?

**Comment by nmasnadithya** [comment]
Thanks for trying out labml. Seems like you're the first to try this on Windows. We haven't tested our library on windows, because we are a small team and it wasn't a priority for us up until now. 

We'll check this and get back as soon as possible. If possible, try using Linux or macOS for the time being?

**Comment by shetsecure** [comment]
Hi, thanks for the fast response.

Yes, as you said it does not work on Windows, and I tried it using Linux.
It works only when using a python script but not with a jupyter notebook

![image](https://user-images.githubusercontent.com/18449334/117538349-14314e00-b006-11eb-9f2a-eae73611f669.png)
![image](https://user-images.githubusercontent.com/18449334/117538369-24492d80-b006-11eb-8f6f-34e6a0f2846c.png)
![image](https://user-images.githubusercontent.com/18449334/117538382-34610d00-b006-11eb-8aad-4e2bd05c100d.png)
![image](https://user-images.githubusercontent.com/18449334/117538395-43e05600-b006-11eb-9e0e-34e942144751.png)

I tried to convert the path into str and created a locally empty git repo, but it still didn't work. ( I'm testing with the same notebook as I mentioned above). Then I suspected that it doesn't have the writing privilege and I run the notebook as root but it gave the same error.
Nevertheless, saving the notebook as a .py file and running it works like a charm.

[INFO]
![image](https://user-images.githubusercontent.com/18449334/117538533-f0bad300-b006-11eb-9652-8922ac5b3d06.png)


Also, do you have any idea why it doesn't work on Windows ?

**Comment by nmasnadithya** [comment]
Glad you could get it working under Linux. Let us have a look on local jupiter notebooks issue.

Did you run the same jupiter notebook to get this error or was it some other notebook?

**Comment by shetsecure** [comment]
Yes it was the same notebook, but I guess the bug is somewhere in the Experiment initializer.
You can simply run this to replicate the issue:

from labml import experiment
experiment.create(name='test')

**Comment by nmasnadithya** [comment]
Thanks. Let us check this and get back to you.

**Comment by nmasnadithya** [comment]
@shetsecure the library update with the fix was published. Let us know whether it resolves your problems

**Comment by shetsecure** [comment]
@nmasnadithya Unfortunately the error still persists on my system...

![image](https://user-images.githubusercontent.com/18449334/117736889-01cb3600-b1f9-11eb-9ed7-a62e922495af.png)

but in colab it works fine
![image](https://user-images.githubusercontent.com/18449334/117737342-fa585c80-b1f9-11eb-9007-7ac7a029f3f7.png)

**Comment by vpj** [comment]
@adrien1018 fixed it
